#!/usr/bin/env bash
#SBATCH --time=4:00:00
#SBATCH --mem=4G

# EXPECTED ENVIRONMENT
# - SLURM_ARRAY_TASK_ID
# - INSTANCES
# - INSTANCES_LIST
# - OFFSET
# - CONTAINER
# - OUTPUT_DIR
# - TIMEOUT_SECS
# - MAX_LOOPS

NR="$(("${OFFSET:=0}" + "$SLURM_ARRAY_TASK_ID"))"

# Pick line `$SLURM_ARRAY_TASK_ID` from the FILE_LIST
file="$(awk "NR == $NR" "$INSTANCES_LIST")"
basefile=$(basename $file)

mkdir -p "$OUTPUT_DIR"

singularity run \
  --env OUTPUT_DIR=/out \
  --bind "$INSTANCES:/in:ro" \
  --bind "$OUTPUT_DIR:/out" \
  $CONTAINER \
  analyse-instance --timeout-secs "$TIMEOUT_SECS" --max-loops "$MAX_LOOPS" --file "/in/$basefile" | tee "$OUTPUT_DIR/$basefile-analysis.json"
